services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    instanceType: "Free"
    branches: 
      - main
    disk: 1GB  # Optional, if you need disk storage
    autoDeploy: true
